# Generated by Django 5.0.1 on 2024-01-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_carrusel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrusel',
            name='imagen',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
