# Generated by Django 3.2.23 on 2024-01-26 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_alter_carouselimage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselimage',
            name='title',
        ),
    ]
