# Generated by Django 5.0.1 on 2024-01-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_profesional', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='reservaCita/')),
                ('google_calendar_url', models.URLField()),
                ('color', models.CharField(max_length=7)),
                ('etiqueta_boton', models.CharField(max_length=255)),
            ],
        ),
    ]
